// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SAN_SoundTuner","status":true,"description":"サウンドチューナー 1.0.0\r\n音声ファイル毎に相対音量、ピッチ、位相を設定します。","parameters":{}}
];
